name: Docker CI/CD

on:
  push:
    branches:
      - feature-jm-sysadm #main
      #- '**'
jobs:
    DockerBuild:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Docker Build
          run: |
            docker build --tag node:23.5.0-alpine3.21 .
    
        - name: Push Docker
          run: |
            docker push node:23.5.0-alpine3.21
    
    DockerScan:
        needs: DockerBuild
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
          
        - name: Docker Login
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Pull Docker
          run: |
            docker pull node:23.5.0-alpine3.21
    
        - name: Run Trivy Scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'node:23.5.0-alpine3.21'
            format: 'table'
    
    Deploy:
        needs: DockerScan
        runs-on: ubuntu-latest
        steps:
          - name: Ejecución de Proceso de despliegue de código
            run: |
              echo "En construcción - Docker Scan"
        