name: DevSecOps-jm-sysadm

on:
  push:
    branches:
      - feature-jm-sysadm
      #- '**'
jobs:
  SAST:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "ORG_NAME=devsecops-jm" >> $GITHUB_ENV

      - name: Validate or Create SonarCloud Project
        id: validate-project
        env:
          DSO_TK_SONARCLOUD: ${{ secrets.DSO_TK_SONARCLOUD_LAB4}}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Verificando si el proyecto $REPO_NAME existe en SonarCloud..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -u "$DSO_TK_SONARCLOUD_LAB4:" \
            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")

          if [ "$response" -ne 200 ]; then
            echo "El proyecto no existe. Creándolo en SonarCloud..."
            create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$DSO_TK_SONARCLOUD_LAB4:" \
              "https://sonarcloud.io/api/projects/create" \
              -d "name=$REPO_NAME" \
              -d "project=$REPO_NAME" \
              -d "organization=$ORG_NAME" \
              -d "visibility=public")

            if [ "$create_response" -ne 201 ]; then
              echo "Proyecto creado exitosamente (HTTP $create_response)."
            fi

            echo "Estableciendo la rama [$BRANCH_NAME] como predeterminada..."
            curl -s -f -X POST -u "$DSO_TK_SONARCLOUD_LAB4:" \
              "https://sonarcloud.io/api/project_branches/rename" \
              -d "name=$BRANCH_NAME" \
              -d "project=$REPO_NAME"

            echo "project_created=true" >> $GITHUB_ENV
          else
            echo "El proyecto ya existe en SonarCloud."
            echo "project_created=false" >> $GITHUB_ENV
          fi

      - name: Perform Initial Analysis (if Project Created)
        run: |
          echo "En construcción"

      - name: Perform Branch Analysis
        if: env.project_created == 'false'
        env:
          DSO_TK_SONARCLOUD: ${{ secrets.DSO_TK_SONARCLOUD_LAB4}}
          REPO_NAME: ${{ github.event.repository.name }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "En construcción"

  SCA:
    needs: SAST
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      run: |
          echo "En construcción"

    - name: Dependency Check
      run: |
          echo "En construcción"
        
    - name: Upload Test Result
      run: |
          echo "En construcción"

  
  DockerBuild:
    needs: SCA
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Docker Login
      run: |
          echo "En construcción"
    
    - name: Deploy Project
      run: |
          echo "En construcción"

    - name: Docker Build
      run: |
          echo "En construcción"

    - name: Push Docker
      run: |
          echo "En construcción"
  DockerScan:
    needs: DockerBuild
    runs-on: ubuntu-24.04
    steps:
    
    - name: Docker Login
      run: |
          echo "En construcción"
    
    - name: Pull Docker
      run: |
          echo "En construcción"

    - name: Run Trivy Scan
      run: |
          echo "En construcción"

    
