name: Example workflow for Node using Snyk
on:
  push:
    branches:
      - feature-jm-sysadm #main
      #- '**'
jobs:
  SCA_SNYK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

# name: SCA

# on:
#   push:
#     branches:
#       - feature-jm-sysadm #main
#       #- '**'
# jobs:
  
#   SCA:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
          
#       # - name: Set up JDK 17
#       #   uses: actions/setup-java@v2
#       #   with:
#       #     java-version: '17'
#       #     distribution: 'adopt'

#       - name: Build project with NPM
#         run: npm install
        
#       - name: Depcheck
#         uses: dependency-check/Dependency-Check_Action@main
#         # env:
#         #   JAVA_HOME: /opt/jdk
#         id: Depcheck
#         with:
#           project: '${{ github.event.repository.name }}'
#           path: '.'
#           format: 'HTML'
#           out: 'reports' # this is the default, no need to specify unless you wish to override it
#           args: >
#             --failOnCVSS 7
#             --enableRetired
            
#       - name: Upload Test results
#         uses: actions/upload-artifact@master
#         with:
#            name: Depcheck report
#            path: ${{github.workspace}}/reports
