name: SCA

on:
  push:
    branches:
      - feature-jm-sysadm #main
      #- '**'
jobs:
  
  SCA:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build project with NPM
        run: npm install
        
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        # env:
        #   JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'HTML'
          out: '.' 
          args: >
            --enableRetired
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
